FROM node:17-alpine3.12

MAINTAINER Lawrence 

WORKDIR /client

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

RUN npm install -g serve


EXPOSE 3000

CMD [ "serve", "-s", "build", "-l", "3000" ]